spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/ourpos
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: true

  sql:
    init:
      platform: h2
      data-locations: classpath:/db/data.sql
      mode: always
      encoding: utf-8

  h2:
    console:
      enabled: true

  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: 2Y9P8poGJG5RED0pEkY7
            client-secret: IlhGjMsPVs
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email,nickname,gender,age,mobile

          kakao:
            client-name: kakao
            client-id: 4ae79b94154d7eb0e20d14f7e344452c
            client-secret: V18MBsV1fyOGptT3UieF2LKm2WtyBClu
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope: profile_nickname,name,gender,age_range,shipping_address,phone_number,talk_message

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  
  jwt:
    secret: asdlkfjsakdlfjklasdjfklasdjsdsadkfjlsdjflks

logging.level:
  org.hibernate.SQL: debug
  # org.hibernate.orm.jdbc.bind: trace

# 프로필 사진이 저장되는 위치 설정
file:
  dir: C:\Users\user\Desktop\한화 PLAYDATA SW캠프\팀프로젝트\최종\메뉴추가\