spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/ourpos
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none # ddl-auto create에서 none으로 수정함
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: true

  sql:
    init:
      platform: h2
      data-locations: classpath:/db/data.sql
      mode: always

  h2:
    console:
      enabled: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.orm.jdbc.bind: trace