spring:
  profiles:
    default: local

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

---
spring:
  config:
    activate:
      on-profile: local, dev, prod