spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: ${local.datasource.url}
    username: ${local.datasource.username}
    password: ${local.datasource.password}
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: true

  sql:
    init:
      platform: h2
      data-locations: classpath:/db/data.sql
      mode: always
      encoding: utf-8

  h2:
    console:
      enabled: true

  data:
    web:
      pageable:
        default-page-size: 5

logging.level:
  org.hibernate.SQL: debug
  # org.hibernate.orm.jdbc.bind: trace

# 프로필 사진이 저장되는 위치 설정
file:
  dir: /Users/sangcheol/image/

# 윈도우는 /Users/sangcheol/image\