spring:
  config:
    activate:
      on-profile: dev

  jackson:
    time-zone: Asia/Seoul

  datasource:
    url: ${dev.datasource.url}
    username: ${dev.datasource.username}
    password: ${dev.datasource.password}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  data:
    web:
      pageable:
        default-page-size: 5

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace

file:
  dir: /home/ubuntu/images/