### 홀 주문 요청

POST http://localhost:8080/api/v1/orders/hall
content-type: application/json
Cookie: Authorization=eyJhbGciOiJIUzI1NiJ9.eyJsb2dpbklkIjoibmF2ZXJfdkZDY25LeFJ2SEEyeFpsajJadUs5T2NWdmhsN2Q2RGdtNS03RUQxV25PVSIsInJvbGUiOiJST0xFX1VTRVIiLCJpYXQiOjE3MTY3ODAzNTcsImV4cCI6MTcxNzM4NTE1N30.OHIBv0VEGgkp7RJPbGKKf5ayhLvi_InqgsS_ObjltRw

{
  "customerId": 2,
  "storeId": 1,
  "orderTakeoutYn": true,
  "orderDetailDtos": [
    {
      "menuId": 1,
      "quantity": 3,
      "orderOptionGroups": [
        {
          "optionGroupName": "사이드 선택",
          "orderOptions": [
            {
              "optionName": "감자튀김",
              "price": 1000
            }
          ]
        }
      ]
    },
    {
      "menuId": 1,
      "quantity": 1,
      "orderOptionGroups": [
        {
          "optionGroupName": "음료 선택",
          "orderOptions": [
            {
              "optionName": "콜라",
              "price": 1000
            }
          ]
        }
      ]
    }
  ]
}

### 홀 주문 조회

GET http://localhost:8080/api/v1/orders/hall/1

### 배달 주문 요청

POST http://localhost:8080/api/v1/orders/delivery
content-type: application/json
Cookie: Authorization=eyJhbGciOiJIUzI1NiJ9.eyJsb2dpbklkIjoibmF2ZXJfdkZDY25LeFJ2SEEyeFpsajJadUs5T2NWdmhsN2Q2RGdtNS03RUQxV25PVSIsInJvbGUiOiJST0xFX1VTRVIiLCJpYXQiOjE3MTY3ODExMzQsImV4cCI6MTcxNzM4NTkzNH0.fBiIVY36IzpToBW7iynOymcI5Mb55o_dzdAeGYVAFho

{
  "customerId": 2,
  "storeId": 1,
  "orderAddressRequestDto": {
    "receiverName": "홍길동",
    "telNo": "010-1234-5678",
    "addressBase": "서울시 강남구 2로",
    "addressDetail": "아파트 101동 101호"
  },
  "ownerMessage": "문 앞에 놔주세요",
  "riderMessage": "빨리 와주세요",
  "tip": 1000,
  "disposableYn": true,
  "orderDetailDtos": [
    {
      "menuId": 1,
      "quantity": 100,
      "orderOptionGroups": [
        {
          "optionGroupName": "사이드 선택",
          "orderOptions": [
            {
              "optionName": "감자튀김",
              "price": 1000
            }
          ]
        }
      ]
    },
    {
      "menuId": 1,
      "quantity": 1,
      "orderOptionGroups": [
        {
          "optionGroupName": "음료 선택",
          "orderOptions": [
            {
              "optionName": "콜라",
              "price": 1000
            }
          ]
        }
      ]
    }
  ]
}



### 배달 주문 조회

GET http://localhost:8080/api/v1/orders/delivery/2

### 점주 홀주문 주문 상세 조회

GET http://localhost:8080/api/v1/manager/orders/hall/1